# Generated by Django 5.2.8 on 2025-11-17 04:42
# flake8: noqa

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('lender', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, choices=[('WORKING_CAPITAL', 'working_capital'), ('INVENTORY', 'inventory'), ('EQUIPMENT', 'equipment'), ('EXPANSION', 'expansion'), ('OPERATIONS', 'operations')], max_length=30, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.FloatField(null=True)),
                ('loan_period', models.FloatField()),
                ('date_of_loan', models.DateField(blank=True, null=True)),
                ('loan_status', models.CharField(choices=[('PAID', 'paid'), ('PENDING', 'pending')], default='PENDING', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_loans', to='business.businessprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('business_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.businessloans')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
