# Generated by Django 5.2.8 on 2025-12-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessloans",
            name="installments_per_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="late_fee_charged",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanrepayment",
            name="payment_is_late",
            field=models.BooleanField(default=False),
        ),
    ]
