# Generated by Django 5.2.8 on 2025-11-17 04:42
# flake8: noqa

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(choices=[('SERVICE', 'Service'), ('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('TECHNOLOGY', 'Technology')], default='SERVICE', max_length=50)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('size', models.CharField(choices=[('0-10', '0-10'), ('10-20', '10-20'), ('20-30', '20-30'), ('30-40', '30-40')], default='0-10', max_length=10)),
                ('operation_period', models.DecimalField(decimal_places=1, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
