# Generated by Django 5.2.8 on 2025-11-17 04:42
# flake8: noqa

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=10, null=True)),
                ('day', models.CharField(blank=True, choices=[('SUN', 'sundayy'), ('MON', 'monday'), ('TUE', 'tuesday'), ('WED', 'wednesday'), ('THUR', 'thursday'), ('FRI', 'friday'), ('SAT', 'saturday'), ('SUN', 'sunday')], max_length=10, null=True)),
                ('is_daily_cashflow', models.BooleanField(blank=True, default=False, null=True)),
                ('cashflow_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('LOAN_INFLOW', 'Loan Inflow'), ('LOAN_REPAYMENT', 'Loan Repayment')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('SALES', 'Sales'), ('STOCK', 'Stock'), ('EMPLOYEE_SALARY', 'Employee Salary')], max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='business.businessprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
