# Generated by Django 5.2.8 on 2025-11-17 05:48
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='day',
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
